package com.scto.mobileide.core.compile.toolchain

import android.content.Context
import com.scto.mobileide.core.util.AndroidSystemLinker
import com.scto.mobileide.core.util.DiagnosticLogFormatter
import timber.log.Timber
import java.io.File
import java.util.Locale

/**
 * 为工具链二进制生成 linker64 shim 脚本。
 */
class ToolchainLinker64ShimManager(
    private val context: Context
) {

    companion object {
        private const val TAG = "ToolchainLinker64Shim"
        internal const val ENV_MOBILE_PROC_SELF_EXE = "MOBILE_EXEC__PROC_SELF_EXE"

        internal fun buildPrepareSummary(
            toolchainBinDir: File,
            rootDir: File?,
            shimDir: File?,
            linker64: String?,
            requestedTools: Set<String>,
            generatedTools: Set<String>
        ): String {
            val missingTools = requestedTools - generatedTools
            return DiagnosticLogFormatter.format(
                prefix = "Toolchain shim prepare",
                "toolchainBinDir" to toolchainBinDir.absolutePath,
                "rootDir" to (rootDir?.absolutePath ?: "<none>"),
                "shimDir" to (shimDir?.absolutePath ?: "<none>"),
                "linker64" to (linker64 ?: "<unknown>"),
                "requestedTools" to formatToolNames(requestedTools),
                "generatedTools" to formatToolNames(generatedTools),
                "missingTools" to formatToolNames(missingTools)
            )
        }

        private fun formatToolNames(tools: Set<String>): String {
            return tools
                .filter { it.isNotBlank() }
                .sorted()
                .joinToString(",")
                .ifBlank { "<none>" }
        }

        internal fun buildShimScript(realBinaryPath: String, linker64Path: String): String {
            val escapedReal = shellSingleQuote(realBinaryPath)
            val escapedLinker = shellSingleQuote(linker64Path)
            return buildString {
                appendLine("#!/system/bin/sh")
                appendLine("# Auto-generated by MobileIDE. Do not edit.")
                appendLine("REAL_BIN='$escapedReal'")
                appendLine("LINKER64='$escapedLinker'")
                appendLine("export $ENV_MOBILE_PROC_SELF_EXE=\"\$REAL_BIN\"")
                appendLine("if [ \"\${MOBILEIDE_TOOLCHAIN_SHIM_TRACE:-0}\" = \"1\" ]; then")
                appendLine("  echo \"MobileIDE shim exec: linker64=\$LINKER64 real=\$REAL_BIN argc=\$#\" >&2")
                appendLine("  echo \"MobileIDE shim env: LD_PRELOAD=\${LD_PRELOAD:-<unset>} MOBILE_EXEC__SYSTEM_LINKER_EXEC__MODE=\${MOBILE_EXEC__SYSTEM_LINKER_EXEC__MODE:-<unset>} MOBILE_EXEC__PROC_SELF_EXE=\${MOBILE_EXEC__PROC_SELF_EXE:-<unset>} MOBILEIDE_LLVM_WRAP_EXEC_LINKER64=\${MOBILEIDE_LLVM_WRAP_EXEC_LINKER64:-<unset>}\" >&2")
                appendLine("fi")
                appendLine("exec \"\$LINKER64\" \"\$REAL_BIN\" \"\$@\"")
            }
        }

        internal fun buildDirectShellShimScript(realBinaryPath: String): String {
            val escapedReal = shellSingleQuote(realBinaryPath)
            return buildString {
                appendLine("#!/system/bin/sh")
                appendLine("# Auto-generated by MobileIDE. Do not edit.")
                appendLine("REAL_BIN='$escapedReal'")
                appendLine("exec \"\$REAL_BIN\" \"\$@\"")
            }
        }

        private fun shellSingleQuote(value: String): String {
            return value.replace("'", "'\"'\"'")
        }
    }

    data class ShimSet(
        val rootDir: File,
        val shimDir: File,
        val toolMap: Map<String, File>
    ) {
        fun shimPath(tool: String): String? = toolMap[tool]?.absolutePath

        fun shellCommandString(tool: String): String? {
            val path = shimPath(tool) ?: return null
            return "/system/bin/sh $path"
        }
    }

    fun prepare(
        toolchainBinDir: File,
        tools: Set<String>
    ): ShimSet? = prepareInternal(
        toolchainBinDir = toolchainBinDir,
        tools = tools,
        modeDirName = "toolchain-shims",
        contentFactory = { realBinary, linker64 ->
            buildShimScript(
                realBinaryPath = realBinary.absolutePath,
                linker64Path = linker64
            )
        }
    )

    fun prepareDirectShell(
        toolchainBinDir: File,
        tools: Set<String>
    ): ShimSet? = prepareInternal(
        toolchainBinDir = toolchainBinDir,
        tools = tools,
        modeDirName = "toolchain-direct-shims",
        contentFactory = { realBinary, _ ->
            buildDirectShellShimScript(realBinaryPath = realBinary.absolutePath)
        }
    )

    private fun prepareInternal(
        toolchainBinDir: File,
        tools: Set<String>,
        modeDirName: String,
        contentFactory: (File, String) -> String
    ): ShimSet? {
        if (!toolchainBinDir.isDirectory) {
            Timber.tag(TAG).w(
                buildPrepareSummary(
                    toolchainBinDir = toolchainBinDir,
                    rootDir = null,
                    shimDir = null,
                    linker64 = null,
                    requestedTools = tools,
                    generatedTools = emptySet()
                )
            )
            return null
        }

        val dirKey = Integer.toHexString(toolchainBinDir.absolutePath.hashCode())
            .lowercase(Locale.ROOT)
        val rootDir = File(context.filesDir, "$modeDirName/$dirKey")
        val shimDir = File(rootDir, "bin")
        val linker64 = AndroidSystemLinker.resolve64BitPreferred()
        if (!shimDir.exists() && !shimDir.mkdirs()) {
            Timber.tag(TAG).w(
                buildPrepareSummary(
                    toolchainBinDir = toolchainBinDir,
                    rootDir = rootDir,
                    shimDir = shimDir,
                    linker64 = linker64,
                    requestedTools = tools,
                    generatedTools = emptySet()
                )
            )
            return null
        }

        val generated = mutableMapOf<String, File>()
        tools.forEach { tool ->
            val realBinary = File(toolchainBinDir, tool)
            if (!realBinary.isFile) return@forEach

            val shimFile = File(shimDir, tool)
            val content = contentFactory(realBinary, linker64)

            val old = runCatching { shimFile.readText() }.getOrNull()
            if (old != content) {
                runCatching { shimFile.writeText(content) }
                    .onFailure { err ->
                        Timber.tag(TAG).w(err, "Failed to write shim for %s", tool)
                    }
            }
            runCatching { shimFile.setExecutable(true, true) }
                .onFailure { err ->
                    Timber.tag(TAG).w(err, "Failed to chmod shim for %s", tool)
                }

            if (shimFile.isFile && shimFile.canExecute()) {
                generated[tool] = shimFile
            } else {
                Timber.tag(TAG).w(
                    "Skip shim for %s because file is not executable: %s",
                    tool,
                    shimFile.absolutePath
                )
            }
        }
        val summary = buildPrepareSummary(
            toolchainBinDir = toolchainBinDir,
            rootDir = rootDir,
            shimDir = shimDir,
            linker64 = linker64,
            requestedTools = tools,
            generatedTools = generated.keys
        )
        if (generated.keys.containsAll(tools)) {
            Timber.tag(TAG).d(summary)
        } else {
            Timber.tag(TAG).w(summary)
        }

        return ShimSet(
            rootDir = rootDir,
            shimDir = shimDir,
            toolMap = generated
        )
    }

}
